# Generated by Django 5.0.3 on 2024-03-11 20:55

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tanks', 'Танки'), ('Healers', 'Хилы'), ('DD', 'ДД'), ('Traders', 'Торговцы'), ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('Smiths', 'Кузнецы'), ('Leatherworkers', 'Кожевники'), ('Potions', 'Зельевары'), ('Spell', 'Мастера заклинаний')], max_length=18, verbose_name='Категория')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст')),
                ('data_creation', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creation', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('content', models.TextField(verbose_name='Текст')),
                ('status', models.CharField(choices=[('undefined', 'Неопределенный'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='undefined', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='board.post', verbose_name='Пост')),
            ],
        ),
    ]
